### ISSUE TITLE
Some species not showing in the network, OpenBabel errors

### ISSUE THREAD

**Issue by mkrompiec** [tongzhugroup/reacnetgenerator#1056]
Thanks for making your code available! I tried to use it to analyze a certain trajectory but I'm getting 5 errors of this type:
*** Open Babel Error  in ParseComplex
  SMILES string contains a character '[' which is invalid
How can I debug this to find out what the offending SMILES was?
Moreover, some species are not displayed in the html (just empty boxes). Nevertheless, OpenBabel is able to generate their depictions correctly, for example via this command:
obabel -ismi s.smiles -osvg
Unfortunately I cannot share my example due to its confidential nature. 
I will appreciate any advice!

**Comment by njzjz** [comment]
https://github.com/tongzhugroup/reacnetgenerator/blob/ce552220a078d6180b0b3cb1712621bada208351/reacnetgenerator/_reachtml.py#L88-L93

Here, OpenBabel is used to generate some svg pictures of species in the html. It doesn't affect anything but just the display. If you need to see what it is in the html, use F12 in the browser, or focus the mouse pointer on the picture and you will see a hint.
Then you can tell me that the species is.

**Comment by mkrompiec** [comment]
Thanks! The "offending" SMILES is correct in the stdout printout from the script:
2021-03-22 17:13:04,685 - ReacNetGen 1.0.0 - INFO: Species are:
2021-03-22 17:13:04,685 - ReacNetGen 1.0.0 - INFO: 1 [H][SH]([H])[Mo](Cl)(Cl)Cl

but incorrect in the HTML:
[H[[S]H([H])[Mo](Cl)(Cl)Cl
Clearly, the nested brackets lead to the error. But how did they get there?

**Comment by njzjz** [comment]
Correctly, there are some tricks to pass the correct number of hydrogen atoms to the OpenBabel, but it fails here. Let me see...

**Comment by mkrompiec** [comment]
Why are these tricks even necessary? I'm not an expert on openbabel, but I thought rdkit should handle explicit hydrogens from SMILES correctly...

**Comment by njzjz** [comment]
> Why are these tricks even necessary? I'm not an expert on openbabel, but I thought rdkit should handle explicit hydrogens from SMILES correctly...

If you use rdkit to convert a methyl radical to SMILES, you will get something like `[H]C([H])[H]`. However, openbabel will consider it as a methane molecule. So, you have to use `[H][C]([H])[H]`, if you need to process some radicals.

**Comment by mkrompiec** [comment]
Thank you! It would be fantastic if you could fix this function so that it works with my molecule.

**Comment by njzjz** [comment]
It should be resolved

**Comment by njzjz** [comment]
> It should be resolved

Sorry, I realized it still has some problems

**Comment by mkrompiec** [comment]
Thanks! Could you make a conda build and a pip wheel?

**Comment by njzjz** [comment]
> Thanks! Could you make a conda build and a pip wheel?

released

**Comment by mkrompiec** [comment]
Thank you so much! Your software works like a treat even on my "exotic" reactive system.
