### ISSUE TITLE
Building from source on an offline machine

### ISSUE THREAD

**Issue by mkrompiec** [tongzhugroup/reacnetgenerator#1062]
I'd like to build reacnetgenerator on our HPC which doesn't have direct internet access. I'm getting the following error:
warning reacnetgenerator-js@1.0.0: License should be a valid SPDX license expression
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/d3/-/d3-3.5.17.tgz: connect ECONNREFUSED 104.16.19.35:443".
info If you think this is a bug, please open a bug report with the information provided in "/home/m212767/conda-install/reacnetgenerator/reacnetgenerator-master/reacnetgenerator/static/webpack/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by njzjz** [comment]
Yes, it will download some third-party packages to build the web page...

**Comment by njzjz** [comment]
You may try to download the latest wheels from https://pypi.org/project/reacnetgenerator/1.4.161/#files, and install them using `pip install <wheel file>`.

**Comment by mkrompiec** [comment]
Thanks, this solves some of the problems. Another issue (from my point of view) is that you require a particular version of NumPy which is not available (yet) in the main anaconda channel. So far, I'm unable to install NumPy 1.20.1 with MKL bindings and the default BLAS causes some other programs to crash. The workaround is to have reacnetgenerator and numpy 1.20.1 in a separate env. So it would be great if you could also make a build with numpy from the default anaconda channel (currently. 1.19.2).

**Comment by njzjz** [comment]
> Thanks, this solves some of the problems. Another issue (from my point of view) is that you require a particular version of NumPy which is not available (yet) in the main anaconda channel. So far, I'm unable to install NumPy 1.20.1 with MKL bindings and the default BLAS causes some other programs to crash. The workaround is to have reacnetgenerator and numpy 1.20.1 in a separate env. So it would be great if you could also make a build with numpy from the default anaconda channel (currently. 1.19.2).

fixed in #1084
