### ISSUE TITLE
Saturated and unsaturated bonds

### ISSUE THREAD

**Issue by Y11190003** [tongzhugroup/reacnetgenerator#1587]
Hello, zeng
My name is Changwei Liu. Can the program count the number of saturated and unsaturated bonds, such as C=O, C=C, or C-C bonds?

**Comment by njzjz** [comment]
The file ending with `.moname` prints all bonds in each species (i.e. SMILES) in column 3. The file ending with `.species` prints the number of species in each frame.

**Comment by Y11190003** [comment]
Is there a script that can extract the number of bonds directly from the relevant file (*.moname, *. species), because I am still stranger to the SMILES processing. The count of the number of bonds has been bothering me for a long time, so thanks for your helps deeply.

**Comment by njzjz** [comment]
> because I am still stranger to the SMILES processing.

Column 3 of the `.moname` file is NOT SMILES. Instead, it's the list of bonds.
