### ISSUE TITLE
Questions on how to count the number of reactants and products

### ISSUE THREAD

**Issue by yunjian-hash** [tongzhugroup/reacnetgenerator#1627]
Dear developers,

I want to count the numer and the distribution of reactants, products and intermediates as a function of the simulation time, as shown in  the attachment figure in your paper. How should I do? Are there some scripts as references for me to learn? Thanks so much
![微信图片_20220714174949](https://user-images.githubusercontent.com/75162924/178955119-f16406ef-dd6d-459f-b789-fb920238918a.png)
![微信图片_20220714174940](https://user-images.githubusercontent.com/75162924/178955130-9641ccfa-ffa4-4185-8b07-8d7454b318b2.png)
!

**Comment by njzjz** [comment]
It will be generated in the `.special` file. You may write your own script to extract what you want to show and plot the results.

**Comment by yunjian-hash** [comment]
> 

Thanks! Is the number behind the chemical formula is in each line is total number of this species? Could you please provide the script, which performed the analyses in the above pictures for me to learn and revise? In fact, I do not know how to manipulate these data due to the poor skills in programming.

**Comment by njzjz** [comment]
A method has been added in #1643, by which one can extract data from the file. See https://reacnetgenerator.njzjz.win/api/reacnetgenerator#module-reacnetgenerator.tools
