### ISSUE TITLE
pip install require high-level nodejs, default nodejs version is 6.13.1, need to upgrade into version 10.x?

### ISSUE THREAD

**Issue by DiracMD** [tongzhugroup/reacnetgenerator#1650]
pip build error following:

_Prepare JavaScript files with webpack...
      yarn install v1.22.19
      [1/5] Validating package.json...
      error reacnetgenerator-js@1.0.0: The engine "node" is incompatible with this module. Expected version ">=10.x". Got "6.13.1"
      error Found incompatible module.
      info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
      Traceback (most recent call last):
        File "<string>", line 29, in run
        File "/home/planck/anaconda3/lib/python3.9/subprocess.py", line 528, in run_

**Comment by njzjz** [comment]
You may need to upgrade to the latest version..
