### ISSUE TITLE
question

### ISSUE THREAD

**Issue by WuhaiD** [tongzhugroup/reacnetgenerator#1712]
Dear developer of reacnetgenerator,
       when i use it to analysis a dump.lammpstrj file, about 1.97 GB, there was an error. That seems that i have to change a size of a certain list. But i don't know how to deal with it. Could you please tell me how can i solve this problem?
![(EFAXEL3AC(KJEJ8}O}~AMU](https://user-images.githubusercontent.com/113823777/191927391-f275b601-1259-4fe9-80d4-24218a49a766.png)
![06ed705ff3aafd44b80bafed9ae0563](https://user-images.githubusercontent.com/113823777/191927408-a4d7acda-20b6-454d-9135-47f9fc425a37.jpg)

**Comment by njzjz** [comment]
Please use the latest version. The issue may have been already fixed by #1636.
