### ISSUE TITLE
How to identify orthorhombic crystals in ReacNetGenerator

### ISSUE THREAD

**Issue by MingjieWen** [tongzhugroup/reacnetgenerator#1943]
Hello, Prof. Zhu and Jin Zhe, when I run ReacNetGenerator, I found that the orthorhombic crystal cannot be recognized, for example: HMX crystal, I would like to ask how to set the coordinates of the orthorhombic crystal in ReacNetGenerator? Thank you very much！
     Best wishes,
     Wen Mingjie

**Comment by MingjieWen** [comment]
> ```
>      Hello, Prof. Zhu and Jin Zhe, when I run ReacNetGenerator, I found that the orthorhombic crystal cannot be recognized, for example: HMX crystal, I would like to ask how to set the coordinates of the orthorhombic crystal in ReacNetGenerator? Thank you very much！
>  Best wishes,
>  Wen Mingjie
> ```

**Comment by Eipgen** [comment]
have you solve this ? you can use the `--cell` parameters to point the box information
