### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by qiuxiaoyue** [tongzhugroup/reacnetgenerator#2113]
Can anyone help with that? This is the problem with "reacnetgenerator --type bond -i bonds.reaxc -a C H O --nohmm"
![微信图片_20240117095649](https://github.com/tongzhugroup/reacnetgenerator/assets/140133356/4e664fe6-34f4-492b-ae7d-395efad37692)

**Comment by Eipgen** [comment]
maybe you can use smaller number processer with `--nproc `

**Comment by qiuxiaoyue** [comment]
> 也许您可以将较小的数字处理器与`--nproc `

Thank you. I'll try.

**Comment by qiuxiaoyue** [comment]
> maybe you can use smaller number processer with `--nproc `

Sorry, I don't understand what you mean, I tried to search this command, but no clue. I would also appreciate your guidance.

**Comment by Eipgen** [comment]
You can specify the number of CPUs to use with `--nproc` https://github.com/tongzhugroup/reacnetgenerator/blob/b942cd7916d43673ebbb02905168b59173e665ef/reacnetgenerator/commandline.py#L78-L83
