### ISSUE TITLE
Can reacnetgeneror support other elements such as N,Al,B,Mg?

### ISSUE THREAD

**Issue by njustcodingjs** [tongzhugroup/reacnetgenerator#877]
Dear developors of reacnetgenerator:
  I am a PhD student studying about energetic materilals. My system contains N and Al elements. I test your program on my systems, but failed. Can reacnetgeneror support other elements such as N,Al,B,Mg?
 Thanks!

**Comment by njzjz** [comment]
It should be OK. What does "failed" mean?
